### ISSUE TITLE
How to Change Host Ip After Payload is Installed

### ISSUE THREAD

**Issue by LoganOneal** [Marten4n6/EvilOSX#1]
How would I go about changing the ip after payload is installed. It will not let me simply reload the payload because I get the "evilosx is already running" message. 
Thank You

**Comment by Marten4n6** [comment]
Use the builder to create a new payload with your new server IP.
Once you are connected to the client you can can run "use update_client", then specify the location to your new payload, the client will then reconnect to your new server IP.

**Comment by Marten4n6** [comment]
- Use the builder to create a payload with your new server IP.
- Once you are connected to the client you can run **use update_client**, then specify the path to your newly built payload. The client will then reconnect to your new server IP.

**Comment by LoganOneal** [comment]
I found a solution. Delete all the files in library. I don't think your
solution would work because you cant connect without the payload running
successfully.

**Comment by Marten4n6** [comment]
With "After payload is installed" I was assuming the client was already connected to the server.
You can also run the following command in terminal (if you named the launch agent this way):
`launchctl remove com.apple.EvilOSX`
