### ISSUE TITLE
Download&upload functions and icloud_phish?

### ISSUE THREAD

**Issue by hyrris** [Marten4n6/EvilOSX#1]
Subj.
And Dont work:
admin@macos-10.13.2.shared:/Users/admin$ use get_info
[I] Running module "get_info"...
admin@macos-10.13.2.shared:/Users/admin$ 
[!] Error executing module: Traceback (most recent call last):
  File "<string>", line 143, in run_module
  File "<string>", line 24, in <module>
  File "<string>", line 12, in get_model
IndexError: list index out of range

Thank u:)

**Comment by Marten4n6** [comment]
Strange, worked fine on the machine I was testing it on.
Please let me know if the latest version fixes this issue, thanks!

**Comment by hyrris** [comment]
```
admin@macos-10.13.2.shared:/Users/admin$ ls
admin@macos-10.13.2.shared:/Users/admin$ 
Applications
Desktop
Documents
Downloads
Library
Movies
Music
Pictures
Public
TEST.py
dd.zip
f.sh
tt.pl
tt.py


admin@macos-10.13.2.shared:/Users/admin$ use download f.sh
[!] That module doesn't exist!
admin@macos-10.13.2.shared:/Users/admin$ use get_info
[I] Running module "get_info"...
admin@macos-10.13.2.shared:/Users/admin$ 
[!] Error executing module: Traceback (most recent call last):
  File "<string>", line 172, in run_module
  File "<string>", line 25, in <module>
  File "<string>", line 14, in get_model
IndexError: list index out of range

```
Server:
python --version
Python 2.7.3

Dont work....

**Comment by Marten4n6** [comment]
![](https://i.imgur.com/8urfsJ9.png)
I'm running the exact same system version as you and the module works fine for me.
Please make sure you are running the latest version of the get_info module (download this repository again).

Could you please post the output of the following commands in a regular terminal:
```bash
# Outputs your system model.
$ sysctl hw.model

# Should output your system model without the "hw.model: " part.
$ sysctl -n hw.model

# Outputs your marketing model.
# Replace NAME with your model name shown in the previous command.
$ /usr/libexec/PlistBuddy -c 'Print:"NAME"' /System/Library/PrivateFrameworks/ServerInformation.framework/Versions/A/Resources/English.lproj/SIMachineAttributes.plist | grep marketingModel
```
This will help me to debug this issue, thanks.

**Comment by hyrris** [comment]
```
macos-10:~ admin$ sysctl hw.model
hw.model: Parallels13,1
macos-10:~ admin$ sysctl -n hw.model
Parallels13,1
macos-10:~ admin$ /usr/libexec/PlistBuddy -c 'Print:"NAME"' /System/Library/PrivateFrameworks/ServerInformation.framework/Versions/A/Resources/English.lproj/SIMachineAttributes.plist | grep marketingModel
Print: Entry, ":NAME", Does Not Exist
```

**Comment by Marten4n6** [comment]
In the last command please replace "NAME" with "Parallels13,1".

**Comment by hyrris** [comment]
```
macos-10:~ admin$ /usr/libexec/PlistBuddy -c 'Print:"Parallels13,1"' /System/Library/PrivateFrameworks/ServerInformation.framework/Versions/A/Resources/English.lproj/SIMachineAttributes.plist | grep marketingModel
Print: Entry, ":Parallels13,1", Does Not Exist
macos-10:~ admin$ 
```

**Comment by Marten4n6** [comment]
It seems you are running in a virtual machine, that's why get_info is unable to get the marketing model.
This should be fixed in the latest version of the module.

Thanks for your help!
(Your other feature requests are being worked on.)

**Comment by hyrris** [comment]
Thank you!
I Will wait for phish root pass and keylogger and then this open source software for now will be best.
