### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by NateJackDev** [Marten4n6/EvilOSX#1]
How would you set this up with a Digital Ocean Server as the server?

**Comment by Marten4n6** [comment]
I haven't used Digital Ocean, you'll need to find out which port is open.
Python should also be installed (which it probably already is).

In terminal:
`git clone https://github.com/Marten4n6/EvilOSX.git`
`cd EvilOSX`
`./BUILDER EvilOSX.py` (enter your external IP and the port which is open)
Then upload and execute the built EvilOSX on your target.
Finally start the server which listens for incoming connections:
`python Server.py`
Done.
