### ISSUE TITLE
Command sudo pip not found

### ISSUE THREAD

**Issue by LxtteDev** [Marten4n6/EvilOSX#103]
I have gone through many tutorials for EvilOSX but i get stuck on all of them when i have to type this command:

sudo pip install -r requirements.txt

The error says: sudo: pip: command not found

am i dumb or is my machine not working?

**Comment by LukeMarston** [comment]
I have the same problem
Does anyone know how to fix it?

**Comment by YulkyTulky** [comment]
You need pip:

https://pip.pypa.io/en/stable/installing/
