### ISSUE TITLE
Script not running

### ISSUE THREAD

**Issue by nmcc1212** [Marten4n6/EvilOSX#106]
I have copied the launcher using sftp to the device then ran it using python Laucherxxxx.py the script ran but then hand after ready without ending so after pressing enter the script ended yet it did not show up, I have rebooted the target device as well but no luck.

I also used pip to install all the requirements onto the target device just in case

**Comment by YulkyTulky** [comment]
Are you building the payload with the GUI or CLI?

**Comment by nmcc1212** [comment]
I have tried both

**Comment by YulkyTulky** [comment]
Then idk what’s wrong. I know there r problems with the GUI builder ... maybe try reinstalling (recloning) the project

**Comment by nmcc1212** [comment]
👍
