### ISSUE TITLE
include the full track trace in code tags? Also have you started the server?

### ISSUE THREAD

**Issue by shellerto** [Marten4n6/EvilOSX#13]
Hi dear
After the update you made.
The error message is given below the running time.

File "<stdin>" Line 1 in <module>
File "/System/Library/Frameworks/Python.framwork/Versions/2.7/lib/urllib2.py" , line 154, in urlopen
return opener.open(url , data , timeout)

and other line erorr

line 431
line 449
line 1240 in https_open

**Comment by Marten4n6** [comment]
Can you please edit your issue to include the full track trace in code tags? Also have you started the server?

**Comment by Fuchsiaff** [comment]
you malware is shit
my 10 year old virus detection detected that shit

**Comment by Marten4n6** [comment]
I mean change the original post to include the ```full stacktrace```, not the title...
If you've started the server is a question you can answer yes or no to.

**Comment by Marten4n6** [comment]
Closed due to inactivity.
