### ISSUE TITLE
OSX Version Requirments

### ISSUE THREAD

**Issue by maxedgerule** [Marten4n6/EvilOSX#16]
I'm doing some testing on older versions of OSX. Do you have a list of versions you have tested against already?

I started with 10.10.4 / python 2.7.6 -
- I couldn't run the client, I was getting a module not found error
- updated to 2.7.14, client can now run.
- The process seems to hang at [INFO] setup_persistence:83 - Done!
-The server sees the client and starts to create the payload but then nothing after that.

**Comment by Marten4n6** [comment]
Unfortunately I only have one Mac which runs the latest version so I am unable to test against earlier versions, Mac virtual machines on Linux are a pain. 
>I was getting a module not found error

Could you please post the stack trace in ```code tags```? This would be very helpful and probably allow me to fix the issue.

>The server sees the client and starts to create the payload but then nothing after that.

The server uses OpenSSL to uniquely encrypt payloads to the target system, do you have OpenSSL installed (system wide)?

**Comment by maxedgerule** [comment]
Oh yeah those osx VMs are a pain...
I'll setup the older version of python again to get the stack trace.

The version of OpenSSL was 0.9.8zd but I then upgraded to 1.0.2o.
- Still the same issue 
Not sure if this matters but each time I try the server shows the following message:
[launch_daemon] Creating payload using key : # 
The key is always the same

If there is anything I can do to help look into this let me know.

**Comment by Marten4n6** [comment]
Tomorrow I'll switch encryption and hashing to use [PyCryptodome](https://github.com/Legrandin/pycryptodome) (maintained fork of PyCrypto). 
Using the system wide OpenSSL was a stupid idea of me lets be honest.

**Comment by Marten4n6** [comment]
Can you let me know if the latest version fixes this?
Note that ```pycryptodomex``` is now a server side dependency.
Cheers!

**Comment by gurn0017** [comment]
I'm trying to run this and am having the error where the process is hanging

**Comment by MysticalCortex** [comment]
def random_string(size: int=None, numbers: bool=False) -> str:

im getting errors with the "size:" colon.

Im on osx 10.13.6

**Comment by Marten4n6** [comment]
@MysticalCortex 
You should be using python3, I've updated the How To Use to specify ```python3``` instead of just ```python```.

@gurn0017 
Can you let me know if the latest version fixes this issue >= v4.0.0?
