### ISSUE TITLE
Modules Not Loading

### ISSUE THREAD

**Issue by cybrly** [Marten4n6/EvilOSX#19]
Once a client connects, the help menu has the following:
help
status
clients
connect <ID>
get_info
kill_client

But the modules fail to load. Thoughts?

**Comment by Marten4n6** [comment]
This is how the help command should look:
![](https://i.imgur.com/lgbOjr4.png)
>the help menu has the following:
>get_info
>kill_client

This was never even in the help command so that's not possible.
What's the output when typing ```modules```? Also are you running the ```python start.py``` command in the EvilOSX directory?

**Comment by Marten4n6** [comment]
Closed due to inactivity.
