### ISSUE TITLE
Error when trying get_info module

### ISSUE THREAD

**Issue by Feners4** [Marten4n6/EvilOSX#2]
After connecting to client, using `get_info` returns `/bin/sh: get_info: command not found`. Any log that would be useful to find out what's going on? Maybe I'm missing something..

**Comment by Marten4n6** [comment]
Seriously... the second message when you start the server is:
`Type "help" to get a list of available commands.`
Run this and you'll see that's not how you use modules, the correct usage is **use get_info**.
