### ISSUE TITLE
stuck on "Creating payload using key: *"

### ISSUE THREAD

**Issue by ayhama00** [Marten4n6/EvilOSX#24]
was able to avoid the error with JSON throwing an exception with bytes by importing codecs, then whenever it runs it stays on the launch_daemon and doesn't advance
![screenshot 2018-06-20 18 20 07](https://user-images.githubusercontent.com/37815546/41687676-964908da-74b6-11e8-97d6-f666d3cf8862.png)

**Comment by Marten4n6** [comment]
The new python version broke some things (which I prefer instead of leaving bloat in the language), can you try >= v4.0.0?

**Comment by ayhama00** [comment]
Hey, the newest v4.0.1 works on this payload end but then the JSON byte issue comes back up, I'll see if i can fix it too, thanks
