### ISSUE TITLE
No module named 'urllib2'

### ISSUE THREAD

**Issue by tinamina12** [Marten4n6/EvilOSX#25]
Hello, i have successfully installed EvilOSX. i created a launcher file and when i try to run that it throws an exception of No module named 'urllib2' and gets stuck there. Since i am a beginner so please apology for stupid question.  i am testing it locally right now i.e. client and server on two different terminals. will it work this way? 
![screen shot 2018-06-22 at 1 57 37 pm](https://user-images.githubusercontent.com/32898278/41767897-47d1292a-7624-11e8-817f-225017a2d975.png)

**Comment by Marten4n6** [comment]
The client side is written in python2, you should be using the command:
```python Launcher-915353.py```
You don't need to use sudo.

Thanks!

**Comment by tinamina12** [comment]
![screen shot 2018-06-22 at 2 27 10 pm](https://user-images.githubusercontent.com/32898278/41769334-6448bd6c-7628-11e8-8b5d-c24a81cee4b4.png)
 still getting the same error. this is maybe because i have only python3 in my system?

**Comment by Marten4n6** [comment]
Can you try use the ```python2``` command? I think it's defaulting to python3 which shouldn't be happening.

**Comment by tinamina12** [comment]
its saying command not found.

**Comment by Marten4n6** [comment]
Can you try the command:
```/usr/bin/python Launcher-X.py```

I think the issue is that the shebang in the Launcher is currently 
```#!/usr/bin/env python```
but should be 
```#!/usr/bin/env python2```

**Comment by tinamina12** [comment]
i have no idea, i tried but still getting the same error. when i do python -V i get 3.6.4 only.

**Comment by Marten4n6** [comment]
It's having trouble finding python2 which should be installed by default on every Mac.
Have you uninstalled it by chance? Also can you post the output of:
```
which -a python python3
```

**Comment by tinamina12** [comment]
![screen shot 2018-06-25 at 8 41 31 am](https://user-images.githubusercontent.com/32898278/41829344-9c15f70a-7853-11e8-9a4d-7168888a16db.png)

**Comment by tinamina12** [comment]
and i noticed one thing more, when i downloaded this code there was no folder of builds and output. i manually created both.  Any idea why is it so? what wrong i am doing?

**Comment by Marten4n6** [comment]
Yeah, my mistake, the newest version automatically creates those directories when running builder.py or start.py (redownload this repository). Try specify the full path to python (which should be version 2): 
```
/usr/bin/python -V
```
Hopefully this command gives you python2.X.X if so please let me know.

**Comment by tinamina12** [comment]
yes finally it is giving Python 2.7.10. But still its giving the same error, no module named urlib2. i cant understand how to use both python 2 and 3 in macos.

**Comment by Marten4n6** [comment]
Can you let me know if the latest version fixes this?
Please redownload the repository and create the launcher again.

Thanks!

**Comment by tinamina12** [comment]
![screen shot 2018-06-25 at 3 12 45 pm](https://user-images.githubusercontent.com/32898278/41844681-5f4730b4-788a-11e8-85c6-a9c9e3f38840.png)
still getting this error. may be i am not setting environment properly.

**Comment by tinamina12** [comment]
yes i identified my mistake, i was not setting environment properly due to which launcher was not working properly. thank you so so so much for your help 👍

**Comment by Marten4n6** [comment]
The python launcher deletes itself after you run it, you were trying to run a file which didn't exist.
Thanks.

**Comment by Woogie20** [comment]
Can you please explain what you did to 'set the environment properly?' No matter what I do I cannot get the launcher to do anything except say: No module named 'urllib2'
