### ISSUE TITLE
Launcher errors out "Could not find domain for"

### ISSUE THREAD

**Issue by quincy7386** [Marten4n6/EvilOSX#26]
I built the launcher w/o issue. The first time I tried it I forgot to add a firewall rule to allow it to communicate with the server. After I opened the port, I ran the python launcher again and got the following error:

[DEBUG] <module>:26 - Program directory: /Users/<user>/Library/Containers/.dCMmfQTuMWrOts
[DEBUG] <module>:27 - Launch agent name: com.apple.KUYViYJMjXmmgfX
[DEBUG] <module>:28 - Payload filename: zSsqaeFlPVdyUGP
[ERROR] <module>:98 - Unexpected output: Could not find domain for

**Comment by Marten4n6** [comment]
Leave out the http:// when creating a launcher, I'm guessing that's the issue.

**Comment by quincy7386** [comment]
I did not use http:// initially as your screen shot just shows the IP. I tried using it to see what happened, and now I do not get the error, but it doesn't connect either. 

I tried adding a host file entry for the IP, but that did not work either.

I captured packets from the client machine, and then ran the launcher again but got no packets.

My setup are VMs running on the same virtual switch. I can ping the the EvilOSX server.

I decoded most of the base64 inside of the launcher and just ran it as a script. I get the domain error and a bunch of packets(20). In the UI I get: 
    [I] [launch_daemon] Creating encrypted payload using key: <key>

Any ideas?

**Comment by Marten4n6** [comment]
Redownload this repository to get the newest version. 
See: https://stackoverflow.com/questions/27189296/homebrew-mxcl-mysql-plist-launchctl-load-error

**Comment by quincy7386** [comment]
I redownloaded the repo, and wasn't sure which part of that post you wanted me to follow, but having the user logged into the UI got me the farthest. No I am get errors in the UI:
![image](https://user-images.githubusercontent.com/15049864/41860980-df6b11ba-7854-11e8-8173-2af8e829f754.png)

**Comment by Marten4n6** [comment]
The new version breaks backwards compatibility, update your bot.
(The update_bot module will be implemented soon)

**Comment by quincy7386** [comment]
I built that bot with the new version, but that was a reminant from a bot that I did not clean up. Works now! Thanks!
