### ISSUE TITLE
browser_history modules throwing error

### ISSUE THREAD

**Issue by tinamina12** [Marten4n6/EvilOSX#27]
when i run use browser_history, i get the following output: 
![screen shot 2018-06-25 at 11 37 08 am](https://user-images.githubusercontent.com/32898278/41845409-d1f2e12e-788c-11e8-8037-acee2eaf3b12.png)
please explain the output.

**Comment by Marten4n6** [comment]
This was already fixed, update your server to a newer version.
See: https://github.com/Marten4n6/EvilOSX/commit/a746f91fea8d70897f23fcf4fdb9e8f8822c5c03
