### ISSUE TITLE
upload module not showing the file uploaded

### ISSUE THREAD

**Issue by tinamina12** [Marten4n6/EvilOSX#30]
when i use upload module it shows no error but i cant see the uploaded file in /tmp folder. 
![screen shot 2018-06-26 at 11 56 54 am](https://user-images.githubusercontent.com/32898278/41894367-1cf6fc0e-7938-11e8-9ca2-438359e544f7.png)

**Comment by Marten4n6** [comment]
Fixed, see https://github.com/Marten4n6/EvilOSX/commit/6465f4a8d4655aa08cee7b21a37063f69144c88f and https://github.com/Marten4n6/EvilOSX/commit/801b777d119ccf4d861d86c52c1404177d6416e6

Thanks!
