### ISSUE TITLE
Can't use modules

### ISSUE THREAD

**Issue by yz55** [Marten4n6/EvilOSX#31]
When trying to use some modules directly on a Mac, I got the following Error. Looks like it can't find the modules in this directory. I tried to move the icloud_contacts.py from the /server to the /bot directory, but that failed also.

![bildschirmfoto 2018-06-27 um 02 33 59](https://user-images.githubusercontent.com/21055442/41946391-9b69b142-79b2-11e8-8ac5-30f607bf0060.png)

If I run the server on Debian (python3) I can't even use the command "modules". I get an "AttributeError" with: 'module' object has no attribute 'module_from_spec'

![screenshot_1](https://user-images.githubusercontent.com/21055442/41946338-46332b72-79b2-11e8-83ec-9a00f89cf422.jpg)

**Comment by Marten4n6** [comment]
Yesterday I forgot to commit the upload module which needed to follow new API changes, this should be the cause of the "modules" command throwing an error.
I'm still re-implementing modules from the old system to the new one, icloud_contacts will be added soon (the error is telling you the code can't be found).

Thanks!

**Comment by yz55** [comment]
Updated, same error on "modules" command

**Comment by Marten4n6** [comment]
The server uses importlib's [module_from_spec](https://docs.python.org/3/library/importlib.html#importlib.util.module_from_spec) to load modules from paths.
This only exists in Python 3.5, not 3.4. Can you try updating python3?
