### ISSUE TITLE
the executable from pyinstaller does not go into background.

### ISSUE THREAD

**Issue by tinamina12** [Marten4n6/EvilOSX#33]
when i create an executable from pyinstaller and run on the victim machine, the executable does not go to the background. please explain this 
<img width="409" alt="test" src="https://user-images.githubusercontent.com/32898278/42088504-1a3b4128-7bb3-11e8-8c15-8924e7b35918.png">

**Comment by Marten4n6** [comment]
The python launcher wasn't made to be used in this way, I'll have a look at supporting [Mach-O](https://en.wikipedia.org/wiki/Mach-O) launchers later.
