### ISSUE TITLE
upload and download modules

### ISSUE THREAD

**Issue by ayhama00** [Marten4n6/EvilOSX#34]
Been noticing this bug with every module whenever text is inputted inside of the input field. Whenever I enter a string and then hit enter to go to the next prompt, the previously entered string gets stuck and freezes the module. 

Example is shown, i used ~/Downloads/example.png for my local directory but i can't delete it or do anything when the next prompt comes up. 
![screenshot 2018-07-01 01 00 31](https://user-images.githubusercontent.com/37815546/42131201-6b9b75ca-7cca-11e8-8834-c8d0fcc55eda.png)

**Comment by Marten4n6** [comment]
This is an issue I was also getting every now and then, threading doesn't like me very much.
Fingers crossed it'll be fixed now...
