### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by marvic2409** [Marten4n6/EvilOSX#41]
Traceback (most recent call last):
File "", line 21, in 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
response = self._open(req, data)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
'_open', req)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
return self.do_open(httplib.HTTPConnection, req)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
raise URLError(err)
urllib2.URLError: <urlopen error [Errno 61] Connection refused>

(I had the server running before the bot was made)

**Comment by Marten4n6** [comment]
Run the server first then run the launcher.

**Comment by marvic2409** [comment]
Run the server (start.py) and the launcher is what?

**Comment by Marten4n6** [comment]
Explain how you're getting that error? Payloads are sent to the background so you won't be able to see anything after the launcher has been run and the payload is successfully loaded.

**Comment by marvic2409** [comment]
Well at first I was using my rubber ducky and I wasn't getting any result, so I decided to paste in the code (Starting with echo) into terminal and seeing the output.

**Comment by Marten4n6** [comment]
>urllib2.URLError: <urlopen error [Errno 61] Connection refused>

Not sure what to tell you, it can't connect to the server to ask for a payload.
Maybe you specified the wrong IP/port (remake a launcher), if you're outside a local network make sure you forward your ports.

**Comment by marvic2409** [comment]
What port should I use, Im currently using 1200

**Comment by Marten4n6** [comment]
That doesn't matter as long as your specify the same thing in the builder and when starting the server.
You can run ```echo YOUR_BASE64_LONG_STRING | base64 --decode | grep -i 'request = '``` to see where the launcher will connect back to, try visit this URL and see if it responds.

**Comment by marvic2409** [comment]
It shows 192.168.1.11:1200 (My local ip) and it does nothing. Did I do
something wrong, why isn't my computer hosting the payload.

**Comment by Marten4n6** [comment]
Hey, thanks very much for this letting me know of this, it was a stupid mistake on my part.
Please redownload this repository and everything should magically work now.

**Comment by marvic2409** [comment]
What was the issue, just wondering

**Comment by Marten4n6** [comment]
You can see every changes I make [here](https://github.com/Marten4n6/EvilOSX/commits/master), the commit that fixed this can be found [here](https://github.com/Marten4n6/EvilOSX/commit/261afeeebc73186bb59a5a98db49cdadb7a53e72).
The problem was that I was starting the user interface (view) before the "background server", it never actually started the background server because the view is blocking, meaning it will not run any other code until it exits. I just overlooked this when I was cleaning up some code...
