### ISSUE TITLE
Phish_itunes not working

### ISSUE THREAD

**Issue by marvic2409** [Marten4n6/EvilOSX#42]
![screen shot 2018-07-10 at 6 27 28 pm](https://user-images.githubusercontent.com/25594875/42522001-c1ef4ac8-8472-11e8-8ce4-4baa56c10f60.png)

**Comment by marvic2409** [comment]
Also it would be cool if a record_webcam feature is implemented.

**Comment by Marten4n6** [comment]
I'm aware of this, this feature isn't currently implemented. Keeping this open until I do implement it.
I'm currently working on a GUI which is more user friendly (you will still be able to use the CLI using the --cli flag).

>Also it would be cool if a record_webcam feature is implemented.

The issue with this is that Macs have a built-in LED (green) which is active if the camera is on.
This would mean that while recording this LED is active and will probably alert the user something's up.

**Comment by marvic2409** [comment]
Yeah but still, it would be a cool feature

**Comment by marvic2409** [comment]
Also would it be possible to implement a secure connection.

**Comment by rwbxn** [comment]
Is this module still not working or am I doing something wrong? That was the best feature and I miss it 💃
