### ISSUE TITLE
Error on server.py on Windows 7

### ISSUE THREAD

**Issue by pedrodj** [Marten4n6/EvilOSX#46]
Hi Marten,

thank for your work: I was trying your RAT on Windows 7 Python 3

**
$ python3 start.py
[!] Failed to print fancy banner, skipping...
[?] Server port to listen on: 2606
Traceback (most recent call last):
  File "start.py", line 87, in <module>
    main()
  File "start.py", line 79, in main
    controller.start()
  File "E:\EvilOSX\server\controller.py", line 42, in start
    self._view.start()
  File "E:\EvilOSX\server\view\cli.py", line 209, in start
    main_loop = urwid.MainLoop(self._frame, self._PALETTE, handle_mouse=True)
  File "C:\Python36\lib\site-packages\urwid\main_loop.py", line 114, in __init__
    screen = raw_display.Screen()
  File "C:\Python36\lib\site-packages\urwid\raw_display.py", line 92, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined
***

Some suggestion?

Regards

**Comment by Marten4n6** [comment]
I dislike Windows very much, I only test this on Linux based systems.
This is a problem with urwid's Windows support, see https://github.com/urwid/urwid/issues/152 and https://github.com/urwid/urwid/issues/240.
A possible solution would be to use https://www.cygwin.com/, please let me know if this works.

Thanks.

**Comment by pedrodj** [comment]
Thank you mate,

I try to fix reporting here the solution :)

Regards

**Comment by Marten4n6** [comment]
I'm working on a fancy GUI, once this is finished you can use this instead of the command line interface and this error won't be a problem.

**Comment by Marten4n6** [comment]
I'm closing this because there is now a GUI which is the default.
