### ISSUE TITLE
When I make the launcher and run it on a friends mac it doesnt work

### ISSUE THREAD

**Issue by UrMUMsDaD** [Marten4n6/EvilOSX#58]
When I make the launcher via terminal and it appear as E.G launcher-1p3p2j49 i try to tun i on a friends mac and nothing happens it just comes up as the code showing rem text all the way down then showing and incrypted paragraph.

i tried running it on a friends mac and nothing happened it was just the same and when i went on the server it said there were no bots can someone please help me with the builder and bot setup part of this

THANKS 
![screen shot 2018-08-01 at 2 48 59 pm](https://user-images.githubusercontent.com/41980676/43501686-23a9b130-959a-11e8-8980-b2a7d0eb0afb.png)
![screen shot 2018-08-01 at 2 47 35 pm](https://user-images.githubusercontent.com/41980676/43501699-2bf042b4-959a-11e8-9571-28ace116daa2.png)

**Comment by Marten4n6** [comment]
See https://github.com/Marten4n6/EvilOSX/issues/56

**Comment by UrMUMsDaD** [comment]
i looked at what u said im still not sure i understand launcher.py does not work for me i do com from c++ so im really not sure sorry

**Comment by Marten4n6** [comment]
You're not supposed to double-click on it, open a terminal and launch it via:
```bash
$ python Launcher.py
```
