### ISSUE TITLE
block some modules

### ISSUE THREAD

**Issue by darl0ck** [Marten4n6/EvilOSX#60]
hello
I wanna block some modules and access to terminal
How can I do this in bot?

**Comment by Marten4n6** [comment]
I have no clue what you're saying.

**Comment by darl0ck** [comment]
Hmm
@Marten4n6 how can I disable access to terminal and some other modules in bot
I wanna that only one or two modules stay
and all another delete from code
and blocks server from using it on mac
Sorry for my bad english :)

**Comment by Marten4n6** [comment]
Not sure why you'd want to do that, modules are sent over the network to the bot, then loaded into memory as they are needed. But to answer your question:
You can remove a module from being picked up by the server by deleting it from [here](https://github.com/Marten4n6/EvilOSX/tree/master/server/modules/server) and [here](https://github.com/Marten4n6/EvilOSX/tree/master/server/modules/bot).
Once you restart the server it will no longer see the deleted module.

Thanks.

**Comment by darl0ck** [comment]
Thanks
And how can I change bot code to disable access to comand-line?
I wanna that it's only show me the mac that was connected and nothing more
if I edit [this](https://github.com/Marten4n6/EvilOSX/blob/master/bot/bot.py) nothing happend

**Comment by darl0ck** [comment]
I resolve it 
Thanks ;)
