### ISSUE TITLE
(error) Code I receive when running certain tasks

### ISSUE THREAD

**Issue by blueman32740** [Marten4n6/EvilOSX#68]
the following occurs when I request to run browser_history, icloud_contacts, and basically 80percents of the available options. 

----
Module server error:
'Pyside2.QtWidgets.QTexitEdit.append' called with wrong argument types:  Pyside2.QtWidgets.QTexitEdit.append(bytes)
Supported Signatures:
Pyside2.QtWidgets.QTexitEdit.append(unicode)
-----

is this the codes issue or do i have to fix, update something ?

**Comment by Marten4n6** [comment]
Issue on my part, I'll fix this when I'm back home.
You can use the command line instead of the GUI in the meantime:
```bash
$ python start.py --cll
```

**Comment by blueman32740** [comment]
usage: start.py [-h] [-p PORT] [--cli] [--builder] [--no-banner]
start.py: error: unrecognized arguments: --cll

**Comment by tinamina12** [comment]
It’s most probably python start.py — cli (2 minus sign. I am commenting from phone, it’s showing minus in a wired way :p )

**Comment by Marten4n6** [comment]
I've dropped GUI support, PySide2 is an absolute pain with it's dependencies and PyQt5 has no python2 support. It may be re-added in the future.
Please let me know if you have any issues with the command line interface.

Thanks.
