### ISSUE TITLE
Error.  sudo

### ISSUE THREAD

**Issue by RickSlimey** [Marten4n6/EvilOSX#69]
When I do, "sudo pip3 install -r requirements.txt" It tells me "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt" What should I do yet I have all of them in the Folder (The Requirements.txt) Please Respond ASAP

**Comment by tinamina12** [comment]
Are you doing cd EvilOSX and then sudo pip3 install -r requirements.txt

**Comment by RickSlimey** [comment]
Yes im doing cd EvilOSX and then sudo pip3 install -requirements.txt

**Comment by Marten4n6** [comment]
You are not in the correct directory, it can't find the requirements.txt file.
The following command shows you the directory you are in:
```bash
$ pwd
```
To change to a directory (assuming the directory is in your downloads folder):
```bash
$ cd ~/Downloads/EvilOSX
```
Please follow the instructions given here:
https://github.com/Marten4n6/EvilOSX#how-to-use

Docker is now also supported, you could use try that.

**Comment by RickSlimey** [comment]
Okay i do not understand, I have found my file now what should I do? The evilosx, requirements.txt is in /Users/rick/Downloads/EvilOSX. I have followed the instructions yet i dont know what to do.

**Comment by Marten4n6** [comment]
Type: ```sudo pip install -r requirements.txt```
I don't see what's difficult about this...
