### ISSUE TITLE
 Kill processing after test rat

### ISSUE THREAD

**Issue by shellerto** [Marten4n6/EvilOSX#7]
Hi
i need remove eviosx from my macbook  .
what should I do To erase it ؟
Sorry, my English is weak

**Comment by Marten4n6** [comment]
You can just run `use remove_client` once you are connected to the client.
If the client for some reason isn't connected to the server, in a terminal run:
```bash
# Remove the launch agent
launchctl remove com.apple.EvilOSX
# Remove the directories
rm -rf ~/Library/Containers/.EvilOSX
rm -rf ~/Library/LaunchAgents/com.apple.EvilOSX
```

**Comment by shellerto** [comment]
![c](https://user-images.githubusercontent.com/31559188/36968615-4bf079b8-2078-11e8-83d3-55b2ce5bd31c.png)

i could not remove client
i see this  error

**Comment by Marten4n6** [comment]
Oops, git closed this issue automatically...
Can you let me know if the latest version fixes this issue?
Thanks.
