### ISSUE TITLE
Untrusted binary executed

### ISSUE THREAD

**Issue by danilo-augusto** [Marten4n6/EvilOSX#76]
Here: https://github.com/Marten4n6/EvilOSX/blob/b159e2bff3348a06010effdfb276300fd985261a/server/modules/bot/webcam.py#L9

Global variable "BINARY". GitHub does not show it because it's a huge line.
I think most of us are not comfortable executing random binary code. 😅

Some clarifications as well as a way to generate such code instead of trusting a gigantic binary would be cool. ;)

Thanks in advance. Very cool repo to analyze some of MacOS weaknesses by the way 🙂

**Comment by danilo-augusto** [comment]
This line:
<img width="1183" alt="proof" src="https://user-images.githubusercontent.com/8104631/46264117-f4198400-c518-11e8-9096-53329fe56e85.png">

To see it on GitHub one should click at "Raw".

**Comment by Marten4n6** [comment]
I'm aware of this, see https://github.com/rharder/imagesnap/issues/26.
That ```BINARY``` variable is just a base64 version of the imagesnap binary, feel free to check the hash.

**Comment by danilo-augusto** [comment]
Thanks for your reply. 🙂
