### ISSUE TITLE
dead sessions after restart system

### ISSUE THREAD

**Issue by shellerto** [Marten4n6/EvilOSX#8]
Hi
i run rat to my macbook and
After running  When the computer restarts
 No access
How to Manually Stable ؟

**Comment by Marten4n6** [comment]
Not really sure how to approach this issue to be honest, persistence works fine on the systems I've tested it on. I've made a lot of changes to EvilOSX recently, maybe it's a good idea to upgrade the server and client to the latest version? In my opinion the current way persistence works sucks (via the launch daemon), I'll be looking into different better ways to make the RAT persistent for sure.

**Comment by Marten4n6** [comment]
Closed due to inactivity.
