### ISSUE TITLE
Error when building with manual launcher. 

### ISSUE THREAD

**Issue by VaXe-Hunter** [Marten4n6/EvilOSX#9]
<img width="489" alt="screenshot" src="https://user-images.githubusercontent.com/6174153/37171518-02f71c10-22c3-11e8-9b4c-803ef2a45102.png">
Not sure why but when building it results with this error. I have all the requirements. Didn't have problems in the last version. Anyone recommend a fix for this?

**Comment by Marten4n6** [comment]
Error on my part, I usually just press "enter" which works fine, give me a few minutes.
Thanks for submitting this issue!
